#! /usr/bin/env zsh

cprint() {
  local color="${1:-white}"
  local message="${2:-}"

  if [ -z "$message" ]; then
    return
  fi

  case "$color" in
    white)
      echo "$message"
      ;;
    yellow)
      printf "\033[1;33m%s\033[0m\n" "$message"
      ;;
  esac
}

# reset goinfre file
# TODO: Make options to choose reset or not
rm -rf ~/goinfre/*
mkdir ~/goinfre/app

# Install Latest VSCode
cprint yellow "Install Latest VSCode..."
curl -L "https://code.visualstudio.com/sha/download?build=stable&os=darwin-universal
" > ~/goinfre/app/code.zip

# Install Brew
# echo "${YELLOW}test"
