#! /usr/bin/env zsh

cprint() {
  local color="${1:-white}"
  local message="${2:-}"

  if [ -z "$message" ]; then
    return
  fi

  case "$color" in
    white)
      echo "$message"
      ;;
    yellow)
      echo "\033[1;33m${message}\033[0m\n"
      ;;
  esac
}

# reset goinfre file
# TODO: Make options to choose reset or not
cprint yellow "Reset goinfre..."
cd ~/goinfre
ls -A1 | xargs rm -rf
cd

mkdir ~/goinfre/app
mkdir ~/goinfre/.poetry


# Install Latest VSCode
# TODO: check VSCode ssh error

# cprint yellow "Install Latest VSCode..."

# curl -L "https://code.visualstudio.com/sha/download?build=stable&os=darwin-universal" > ~/goinfre/app/code.zip
# unzip ~/goinfre/app/code.zip -d ~/goinfre/app


# Install Brew
cprint yellow "Install Latest Brew..."
git clone --depth=1 https://github.com/Homebrew/brew $brewPath/.brew && source $HOME/.zshrc 2>/dev/null && brew update
brewPath="$(brew --prefix)"

# Install ncdu@1
brew tap OctopusET/42
brew install ncdu@1
brew link ncdu@1

# Install pyenv
brew install pyenv
brew install xz
pyenv install 3.10.11
pyenv global 3.10.11

# Install poetry
curl -sSL https://install.python-poetry.org | POETRY_HOME=/Users/sunpark/goinfre/.poetry python3