#! /usr/bin/env zsh

cprint() {
  local color="${1:-white}"
  local message="${2:-}"

  if [ -z "$message" ]; then
    return
  fi

  case "$color" in
    white)
      echo "$message"
      ;;
    yellow)
      echo "\033[1;33m${message}\033[0m\n"
      ;;
  esac
}

# reset goinfre file
# TODO: Make options to choose reset or not
cprint yellow "Reset goinfre..."
cd ~/goinfre
ls -A1 | xargs rm -rf
cd

mkdir ~/goinfre/app
mkdir ~/goinfre/.poetry
mkdir ~/goinfre/.vagrant.d

# Install Latest VSCode
cprint yellow "Install Latest VSCode..."
curl -L "https://code.visualstudio.com/sha/download?build=stable&os=darwin-universal" > ~/goinfre/app/code.zip
unzip -qq ~/goinfre/app/code.zip -d ~/goinfre/app
rm -rf ~/goinfre/app/code.zip

defaults write com.apple.systempreferences AttentionPrefBundleIDs 0 && killall Dock

# Install Brew
cprint yellow "Install Latest Brew..."
git clone --depth=1 https://github.com/Homebrew/brew $brewPath/.brew && source $HOME/.zshrc 2>/dev/null && brew update
brewPath="$(brew --prefix)"

# Install ncdu@1
#brew tap OctopusET/42
#brew install ncdu@1
#brew link ncdu@1

# Install pyenv
brew install pyenv
brew install xz
pyenv install 3.10.12
pyenv global 3.10.12

source $HOME/.zshrc 2>/dev/null

# Install poetry
curl -sSL https://install.python-poetry.org | python -
source $HOME/.zshrc 2>/dev/null

pip install pre-commit

# brew install libpq
# brew link --force libpq
