#! /usr/bin/env zsh

cprint() {
  local color="${1:-white}"
  local message="${2:-}"

  if [ -z "$message" ]; then
    return
  fi

  case "$color" in
    white)
      echo "$message"
      ;;
    yellow)
      echo "\033[1;33m${message}\033[0m\n"
      ;;
  esac
}

# git basic settings
git config --global user.name "Sungwoo Park"
git config --global user.email codest99@gmail.com
git config --global core.precomposeunicode true
git config --global core.quotepath false

# zsh settings
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k

# ssh settings
ssh-keygen -t ed25519 -C "codest99@gmail.com"
eval "$(ssh-agent -s)"
mkdir ~/.ssh/config
echo "Host github.com\n  AddKeysToAgent yes\n  UseKeychain yes\n  IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config
ssh-add -K ~/.ssh/id_ed25519
pbcopy < ~/.ssh/id_ed25519.pub
cprint yellow "SSH key copied! paste at github and intra!"
